.gitignore
README.md
copy_files_to_derivatives.py
manual_correction.py
package_for_correction.py
requirements.txt
utils.py

This PR proposes an initial version of scripts for manual correction workflow. For details, see [README](https://github.com/spinalcordtoolbox/manual-correction/blob/jv/generalize_manual_correction_scripts/README.md).
The scripts are based on [ukbiobank-spinalcord-csa](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa) scripts. To allow easy tracking of changes proposed in this PR, I pushed the `ukbiobank-spinalcord-csa` scripts to the [main branch](https://github.com/spinalcordtoolbox/manual-correction).
Compared `ukbiobank-spinalcord-csa` scripts, I added:
- new input flags (`-path-derivatives`,  `-path-derivatives`, `-suffix-files-seg`, `-suffix-files-gmseg`, `-suffix-files-label`, `-label-list`, `-viewer`) in https://github.com/spinalcordtoolbox/manual-correction/commit/f89a9acec …

Generalize manual correction scripts

---

manual_correction.py
requirements.txt
utils.py

This PR adds a feature that creates an empty mask if segmentation does not exist. This is useful, for example, when creating MS lesion segmentations from scratch. 
Please, could you double-check especially the part of the code responsible for empty mask creation:
https://github.com/spinalcordtoolbox/manual-correction/blob/bba77adbb97f28fa68c5c13a4b81e69a8e547331/utils.py#L254-L264
Fixes https://github.com/spinalcordtoolbox/manual-correction/issues/4

Allow creation of empty mask

---

manual_correction.py
package_for_correction.py

This PR addresses the [request](https://github.com/ivadomed/canproco/issues/20#issue-1560071285) from the canproco project about the possibility of opening additional contrast within a single FSLeyes window. For example, T2w image overlaid by PSIR image.
Namely, this [PR adds](https://github.com/spinalcordtoolbox/manual-correction/commit/9f31ba4f7c823b447e4639ef6b15af235ee5ec7d):
- `'-load-other-contrast'` flag for loading an additional image to the viewer (currently, only FSLeyes is supported)
- `-denoise` flag for denoising the input image using 'sct_maths -denoise p=1,b=2'.
Flags can be used together or separately.
~~The PR also contains ["hacky" commit](https://github.com/spinalcordtoolbox/manual-correction/commit/28ada98b99e297aed4ca504fec659968b93ed883) for the opening of the …

Load additional contrast + allow denoising

---

manual_correction.py
package_for_correction.py
utils.py

This PR adds the possibility to iterate across all subjects using the wildcard `*`.
The config file then looks like:
```yaml
FILES_SEG:
- sub-*_T1w.nii.gz
```
Fixes https://github.com/spinalcordtoolbox/manual-correction/issues/5

Allow iterating across all subjects using wildcard

---

utils.py

This PR improves the clarity of log by adding warning color to the output of the function `check_files_exist`

Add clarity with warning color to log output for missing files and labels

---

README.md
manual_correction.py
package_for_correction.py

The PR adds proper compression labeling.
How to test:
```console
cd <PATH_TO_DATASET>/dcm-zurich
python <PATH_TO_REPO>/manual_correction.py -config config.yml -path-in . -load-other-contrast acq-sagittal_T2w
```
example config.yml:
```yml
FILES_COMPRESSION:
- sub-250791_acq-axial_T2w.nii.gz
- sub-260155_acq-axial_T2w.nii.gz
```
I also updated [wiki](https://github.com/spinalcordtoolbox/manual-correction/wiki#manual-labeling-of-spinal-cord-compression). 
Fixes: https://github.com/spinalcordtoolbox/manual-correction/issues/36

Allow compression labeling

---

manual_correction.py
utils.py

This PR drop warnings raised by `check_files_exist` function when running another round of corrections.
The [check_files_exist](https://github.com/spinalcordtoolbox/manual-correction/blob/6d1e028baa3c959ccbef367d6420b8dc2ed65635/utils.py#L198) function now newly checks (see [here](https://github.com/spinalcordtoolbox/manual-correction/blob/6d1e028baa3c959ccbef367d6420b8dc2ed65635/utils.py#L220-L229)) if labels exist under `derivatives` folder. If so, no warning is raised (because we will be editing precisely these labels under `derivatives`).
Main branch:
This branch:
Resolves: #38

Limit warnings raised by `check_files_exist`

---

manual_correction.py
tests/test_utils.py
utils.py

This PR addresses several issues related to path use with manual correction script
To avoid future confusions regarding the [different use cases](https://github.com/spinalcordtoolbox/manual-correction/issues/44) of the script `manual_correction.py`, this PR allows the user to directly specify:
- the folder where images are stored using `-path-img`
- the folder where labels are stored using `-path-label`
- the folder where corrected labels will be stored using `-path-out`
Some additions to code were also done to improve robustness regarding the use of the "-manual" suffix and more, see related issues.
https://github.com/spinalcordtoolbox/manual-correction/issues/51
https://github.com/spinalcordtoolbox/manual-correction/issues/47
https://github.com/spinalcordtoolbox/manual-correction/issues/ …

Fix path confusion when using `manual_correction.py`

---

manual_correction.py
tests/test_utils.py
utils.py

This PR fixes wildcard (`*`) handling.
Resolves: https://github.com/spinalcordtoolbox/manual-correction/issues/35

Fix wildcard handling

---

manual_correction.py

Replace all the `os.system` shell calls with `subprocess.check_call` to catch keyboard interrupts to stop the code

Use subprocess instead of os.system to catch keyboardInterrupts

---

.github/workflows/ci.yml
manual_correction.py

Check if the label file is empty (i.e., no lesion was drawn in MS patient); if so, skip QC.
Resolves: https://github.com/spinalcordtoolbox/manual-correction/issues/60

Skip QC if label file is empty

---

manual_correction.py
tests/test_utils.py
utils.py

The script now skips unsupported tasks. For example, for the following config file:
```yml
FILES_REG:
- sub-001_T2w.nii.gz
FILES_SEG:
- sub-*_T2w.nii.gz
```
The script now prints warning and skips `FILES_REG`:
```console
...
WARNING: FILES_REG is not a valid task. Skipping it.
...
```
Resolves: https://github.com/spinalcordtoolbox/manual-correction/issues/71

Handle KeyErrors more gracefully if user marks `FILES_REG` as a `qc_fail.yml`

---

.github/workflows/ci.yml

To address the following warning from Github Actions:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Upgrade node12 actions

---

manual_correction.py
tests/test_create_json.py

Updated description based on https://github.com/spinalcordtoolbox/manual-correction/pull/76#issuecomment-1939082475:
This PR adds new key-value pairs `SpatialReference': 'orig'` and `'Name': 'Manual'` into JSON sidecars:
```json
{
"SpatialReference": "orig",
"GeneratedBy": [
{
"Name": "Manual",
"Author": "Test Rater",
"Date": "2024-02-14"
}
]
}
```
The PR also removes the `check_if_modified` function; for context see https://github.com/spinalcordtoolbox/manual-correction/pull/76#issuecomment-1939147742.
<details><summary>Original description</summary>
This PR proposes a new key-value pair `"Note"` to track if a label was only visually inspected or manually modified. To determine between these two scenarios, the already existing [`check_if_modified` …

Add `"Name"` and `"SpatialReference"` key-value pair to JSON sidecar 

---

manual_correction.py
tests/test_create_json.py

This PR adds a new `-json-metadata` flag to allow you to specify a custom JSON file containing metadata to be added to the JSON sidecar of all corrected labels.
This flag is useful, for example, when a label was obtained automatically, and you want to include this information into the JSON sidecar.
---
Example usage:
```console
python manual_correction.py -path-img ~/data/site-001_2024-02-21/data_processed/ -path-label ~/data/site-001_2024-02-21/data_processed/ -path-out ~/data/site-001/derivatives/labels/ -config sc_seg_to_correct_t2w.yml -json-metadata custom_metadata.json
```
where `custom_metadata.json`:
```json
{
"Name": "sct_deepseg_sc",
"Version": "SCT v6.2",
"Date": "2024-02-21"
}
```
The output JSON sidecar then looks like this:
```json
{
"SpatialReference": "orig", …
```

Allow to specify custom metadata to be included in JSON sidecars

---

manual_correction.py

This is a minor PR removing date/time for the QC folder. Now, even when the manual correction workflow is stopped and resumed, all QCs are saved under the save folder `qc_corr`.
Resolves: https://github.com/spinalcordtoolbox/manual-correction/issues/91

Do not use date/time for the QC folder

---

manual_correction.py
utils.py

Reverts spinalcordtoolbox/manual-correction#88 to solve issues mentioned in #93

Revert "Add options for sub-folder and for func sesssions"

---

manual_correction.py
utils.py

This PR is about adding an option to view images and labels in a different orientation than the original. This can be useful for "easier" correction with different orientation. 
Resolves [#99](https://github.com/spinalcordtoolbox/manual-correction/issues/99)

Add an option to specif the orientation to show the image in the viewer

---

.github/workflows/ci.yml
README.md
manual_correction.py
tests/test_utils.py
utils.py

This draft PR adds an option to correct rootlets segmentation.
Resolves: [#56](https://github.com/spinalcordtoolbox/manual-correction/issues/56)

Add support for spinal rootlets segmentation

---

manual_correction.py

As SCT v6.4+ produces JSON sidecars for some outputs that track the provenance of the function, models, etc. (details: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4466), we want to include this information in the final JSON sidecar produced by `manual_correction.py`.  This PR implements this feature.
```console
cd ~/code/manual-correction
git fetch
git checkout jv/103_include_json_created_by_sct
```
```console
sct_download_data -d sct_course_data -o sct_course_data_2024
cd sct_course_data_2024/multi_subject
chmod +x process_data.sh
sct_run_batch -script process_data.sh -config config.yml -jobs 3
$SCT_DIR/python/envs/venv_sct/bin/python ~/code/manual-correction/manual_correction.py -config qc_fail.yml -path-img output/data_processed/ -path-label output/data_processed …
```

Include JSON metadata created by SCT

---

manual_correction.py

This PR changes the default value for `-path-label` to match `-path-img`. Context: https://github.com/spinalcordtoolbox/manual-correction/issues/104
The change simplifies the `manual_correction.py` syntax as used for the SCT course to
```
manual_correction.py -config qc_fail.yml -path-img output/data_processed/ -path-out data/derivatives/labels
``` 
(i.e., we do not need to specify `-path-label` now, as it is automatically set to `-path-img`)
```bash
cd ~/code/manual-correction
git fetch
git checkout jv/104-set_path-label_to_path-img
```
```bash
sct_download_data -d sct_course_data -o sct_course_data_2024
cd sct_course_data_2024/multi_subject
chmod +x process_data.sh
sct_run_batch -script process_data.sh -config config.yml -jobs 3
$SCT_DIR/python/envs/venv_sct/bin/python …
```

Set the default value for `-path-label` to match `-path-img`

---

manual_correction.py

This PR adds a new input argument `-fsleyes-a` to adjust the opacity of the label file (e.g., segmentation).

Add input arg to set opacity for labels

---

package_for_correction.py

We want to copy not only NIfTI files but also JSON sidecars because they track which model was used to generate the NIfTI files.

`package_for_correction.py`: copy also JSON sidecars

---

utils.py

This PR fixes the failing CI for `test_get_orientation`:
SCT now adds an extra line with total runtime at the end of its output. Example:
```
--
Spinal Cord Toolbox (git-jv/sct_process_segmentation_use_hog-2825761400b80fa7d556d24356f78e437c664496*)
sct_image -i /private/var/folders/v3/00vnhxcj5vg7d7mr7r4vl5sr0000gn/T/pytest-of-valosek/pytest-3/test_get_orientation0/BIDS/sub-001/ses-01/anat/sub-001_ses-01_T1w.nii.gz -getorient
--
LPI
Total runtime; 0.150 seconds.
```
We thus need to strip one extra line to get `LPI`.

Fix orientation extraction from `sct_image` output
